apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: myminio-console
  namespace: minio-tenant
spec:
  port:
    targetPort: https-console
  tls:
    termination: passthrough
  to:
    kind: ""
    name: myminio-console
